=== Cyan256X/Cyan256X.github.io/holoprint/data/schemas/materialListMappings.schema.json
{"$schema":"http://json-schema.org/draft-07/schema#","title":"Material list mappings","description":"Patches and other mappings for MaterialList.js.","type":"object","properties":{"$schema":{"type":"string"},"ignored_blocks":{"description":"An array of blocks that will be ignored and will not be put in material lists.","type":"array","items":{"description":"Block name.","type":"string","minLength":1}},"block_to_item_mappings":{"description":"Mappings for blocks that have different item names. If a block isn't found here, the item name is assumed to be the same as the block name. Regular expressions will be checked only if no individual match is found.","type":"object","patternProperties":{"^\\w+$":{"description":"\"block_name\": \"item_name\"","type":"string","minLength":1},"^/.+/$":{"description":"\"regular expression\": \"item_name\"","type":"string","minLength":1}},"additionalProperties":false},"item_count_multipliers":{"description":"Items that will have their count multiplied by a certain amount.","type":"object","patternProperties":{"^(\\w+|/[^,]+/)(,(\\w+|/[^,]+/))*$":{"oneOf":[{"description":"Multiplier.","type":"number","exclusiveMinimum":0},{"description":"Item names separated by commas. Regular expressions can be used with /.../.","type":"object","properties":{"multiplier":{"description":"Multiplier.","type":"number","exclusiveMinimum":0},"remove":{"description":"Will remove all instances of this from the item name.","type":"string","minLength":1}},"required":["multiplier","remove"],"additionalProperties":false}]}},"additionalProperties":false},"special_block_entity_properties":{"description":"Definitions for blocks that should be split up based on a numeric block entity property.","type":"object","patternProperties":{"^\\w+$":{"description":"Block name.","type":"object","properties":{"prop":{"description":"Block entity property name.","type":"string","minLength":1},"serialization_ids":{"description":"Serialization ID remappings.","type":"array","items":{"description":"Serialization ID.","type":"string"},"minItems":1}},"required":["prop"],"additionalProperties":false}},"additionalProperties":false},"serialization_id_patches":{"description":"Remappings for serialization_ids that go to the wrong things in .lang files. Regular expressions will be checked only if no individual match is found.","type":"object","patternProperties":{"^(tile|item)\\.\\w+$":{"description":"Serialization ID.","type":"string","pattern":"^(tile|item)\\.[\\w.]+$"},"^/.+/$":{"description":"Regular expressions to match serialization IDs.","type":"string","minLength":1}},"additionalProperties":false},"blocks_missing_serialization_ids":{"description":"Patches for blocks that don't have any serialization ID due to not existing in mojang-blocks.json despite existing in-game.","type":"object","patternProperties":{"^\\w+$":{"description":"\"block_name\": \"serialization_id\"","type":"string","minLength":1}},"additionalProperties":false},"translation_patches":{"description":"Translations that don't exist for whatever reason.","type":"object","patternProperties":{"^(tile|item)\\.[\\w.]+$":{"description":"\"serialization_id\": \"Translated Item Name\"","type":"string","minLength":1}},"additionalProperties":false}},"required":["ignored_blocks","block_to_item_mappings","item_count_multipliers","special_block_entity_properties","serialization_id_patches","blocks_missing_serialization_ids","translation_patches"],"additionalProperties":false}

=== Cyan256X/Cyan256X.github.io/holoprint/data/materialListMappings.json
{"ignored_blocks":["flowing_water","flowing_lava","bubble_column"],"block_to_item_mappings":{"unpowered_repeater":"repeater","powered_repeater":"repeater","unpowered_comparator":"comparator","powered_comparator":"comparator","redstone_wire":"redstone","unlit_redstone_torch":"redstone_torch","water":"water_bucket","lava":"lava_bucket","powder_snow":"powder_snow_bucket","lit_furnace":"furnace","lit_blast_furnace":"blast_furnace","lit_smoker":"smoker","lit_redstone_ore":"redstone_ore","lit_deepslate_redstone_ore":"deepslate_redstone_ore","lit_redstone_lamp":"redstone_lamp","reeds":"sugar_cane","melon_stem":"melon_seeds","pumpkin_stem":"pumpkin_seeds","pitcher_crop":"pitcher_pod","torchflower_crop":"torchflower_seeds","wheat":"wheat_seeds","potatoes":"potato","carrots":"carrot","wall_sign":"oak_sign","standing_sign":"oak_sign","darkoak_wall_sign":"dark_oak_sign","darkoak_standing_sign":"dark_oak_sign","bamboo_sapling":"bamboo","trip_wire":"string","cocoa":"cocoa_beans","wall_banner":"standing_banner","cave_vines":"glow_berries","cave_vines_body_with_berries":"glow_berries","cave_vines_head_with_berries":"glow_berries","/^(\\w+)_wall_sign$/":"$1_sign","/^(\\w+)_standing_sign$/":"$1_sign","/^(\\w+)_coral_wall_fan$/":"$1_coral_fan"},"item_count_multipliers":{"/double_.*slab$/":{"multiplier":2,"remove":"double_"},"/_door$/":0.5,"peony,rose_bush,sunflower,lilac,large_fern,tall_grass,pitcher_plant":0.5,"bed":0.5},"special_block_entity_properties":{"bed":{"prop":"color","serialization_ids":["item.bed.white","item.bed.orange","item.bed.magenta","item.bed.lightBlue","item.bed.yellow","item.bed.lime","item.bed.pink","item.bed.gray","item.bed.silver","item.bed.cyan","item.bed.purple","item.bed.blue","item.bed.brown","item.bed.green","item.bed.red","item.bed.black"]}},"serialization_id_patches":{"tile.oak_planks":"tile.planks.oak","tile.spruce_planks":"tile.planks.spruce","tile.birch_planks":"tile.planks.birch","tile.jungle_planks":"tile.planks.jungle","tile.acacia_planks":"tile.planks.acacia","tile.dark_oak_planks":"tile.planks.big_oak","tile.oak_fence":"tile.fence","tile.spruce_fence":"tile.spruceFence","tile.birch_fence":"tile.birchFence","tile.jungle_fence":"tile.jungleFence","tile.acacia_fence":"tile.acaciaFence","tile.dark_oak_fence":"tile.darkOakFence","item.water_bucket":"item.bucketWater","item.lava_bucket":"item.bucketLava","item.powder_snow_bucket":"item.bucketPowderSnow","tile.wall_banner":"tile.standing_banner","tile.daylight_detector_inverted":"tile.daylight_detector","tile.tube_coral_wall_fan":"tile.coral_fan.blue_fan.name","tile.brain_coral_wall_fan":"tile.coral_fan.pink_fan.name","tile.bubble_coral_wall_fan":"tile.coral_fan.purple_fan.name","tile.fire_coral_wall_fan":"tile.coral_fan.red_fan.name","tile.horn_coral_wall_fan":"tile.coral_fan.yellow_fan.name","tile.dead_tube_coral_wall_fan":"tile.coral_fan_dead.blue_fan.name","tile.dead_brain_coral_wall_fan":"tile.coral_fan_dead.pink_fan.name","tile.dead_bubble_coral_wall_fan":"tile.coral_fan_dead.purple_fan.name","tile.dead_fire_coral_wall_fan":"tile.coral_fan_dead.red_fan.name","tile.dead_horn_coral_wall_fan":"tile.coral_fan_dead.yellow_fan.name","tile.seagrass":"tile.seagrass.seagrass","item.creeper_head":"item.skull.creeper","item.dragon_head":"item.skull.dragon","item.piglin_head":"item.skull.piglin","item.player_head":"item.skull.char","item.skeleton_skull":"item.skull.skeleton","item.wither_skeleton_skull":"item.skull.wither","item.zombie_head":"item.skull.zombie","item.cocoa_beans":"item.dye.brown","item.white_dye":"item.dye.white_new","item.bone_meal":"item.dye.white","item.dark_oak_boat":"item.boat.big_oak","item.dark_oak_chest_boat":"item.chest_boat.big_oak","/^item.(?!.*chest_)(\\w+)_(boat|raft)$/":"item.boat.$1","/^item.(\\w+)_chest_(boat|raft)$/":"item.chest_boat.$1"},"blocks_missing_serialization_ids":{"end_gateway":"tile.end_gateway"},"translation_patches":{"tile.end_portal.name":"End Portal","tile.end_gateway.name":"End Gateway"},"$schema":"schemas/materialListMappings.schema.json"}
