=== Cyan256X/Cyan256X.github.io/holoprint/data/schemas/textureAtlasMappings.schema.json
{"$schema":"http://json-schema.org/draft-07/schema#","title":"Texture atlas mappings","description":"Patches and other mappings for TextureAtlas.js.","type":"object","properties":{"$schema":{"type":"string"},"blocks_dot_json_patches":{"description":"Block names that need to be remapped to something else in blocks.json.","type":"object","patternProperties":{"^\\w+$":{"description":"Block names, with _._ meaning variants.","type":"string","pattern":"^\\w+(\\.\\d+)?$"}},"additionalProperties":false},"blocks_to_use_carried_textures":{"description":"An array of block names that should use their carried textures.","type":"array","items":{"description":"Block name.","type":"string","minLength":1}},"transparent_blocks":{"description":"Blocks that are transparent and need a certain opacity applied to them.","type":"object","patternProperties":{"^\\w+$":{"description":"Block name and opacity.","type":"number","exclusiveMinimum":0}},"additionalProperties":false},"terrain_texture_tints":{"description":"Terrain texture keys that should have their textures tinted.","type":"object","properties":{"colors":{"description":"Tint colour definitions.","type":"object","patternProperties":{"^\\w+$":{"description":"Tint colour -> 6-digit hex colour.","type":"string","pattern":"^#[\\da-fA-F]{6}$"}},"additionalProperties":false},"terrain_texture_keys":{"description":"The actual terrain texture keys that should have tints applied.","type":"object","patternProperties":{"^\\w+$":{"oneOf":[{"$ref":"#/definitions/tintColor"},{"description":"A tint colour and a flag to make it be tinted like a PNG image.","type":"object","properties":{"tint":{"$ref":"#/definitions/tintColor"},"tint_like_png":{"description":"If true, the image will be tinted as if it were a PNG image, despite being a TGA image. (TGA images are tinted different to PNG images.)","type":"boolean","default":true}},"required":["tint","tint_like_png"],"additionalProperties":false}]}}}},"additionalProperties":false},"missing_flipbook_textures":{"description":"File paths of flipbook textures that aren't used in-game because they're missing from flipbook_textures.json. This fixes up their UV coordinates.","type":"array","items":{"description":"Texture path.","type":"string","pattern":"^textures/.*[^/]$"}}},"required":["blocks_dot_json_patches","blocks_to_use_carried_textures","transparent_blocks","terrain_texture_tints","missing_flipbook_textures"],"additionalProperties":false,"definitions":{"tintColor":{"oneOf":[{"description":"A tint colour, as defined in the \"colors\" property.","type":"string","pattern":"^\\w+$"},{"description":"A tint colour.","type":"string","pattern":"^#[\\da-fA-F]{6}$"}]}}}

=== Cyan256X/Cyan256X.github.io/holoprint/data/textureAtlasMappings.json
{"blocks_dot_json_patches":{"grass_block":"grass","trip_wire":"tripWire","sea_lantern":"seaLantern","iron_chain":"chain","unknown":"info_update"},"blocks_to_use_carried_textures":["acacia_leaves","birch_leaves","bush","dark_oak_leaves","fern","firefly_bush","leaves","leaves2","mangrove_leaves","oak_leaves","open_eyeblossom","short_grass","spruce_leaves","vine","waterlily"],"transparent_blocks":{"water":0.65,"flowing_water":0.65,"slime":0.8,"respawn_anchor":2},"terrain_texture_tints":{"colors":{"foliage":"#79C05A","water":"#44AFF5"},"terrain_texture_keys":{"grass_top":"foliage","tall_grass_bottom":{"tint":"foliage","tint_like_png":true},"tall_grass_top":{"tint":"foliage","tint_like_png":true},"large_fern_bottom":{"tint":"foliage","tint_like_png":true},"large_fern_top":{"tint":"foliage","tint_like_png":true},"reeds":{"tint":"foliage","tint_like_png":true},"jungle_leaves":{"tint":"#57BE08","tint_like_png":true},"leaf_litter":"#A36D46","flowing_water_grey":"water","flowing_water":"water","still_water_grey":"water","still_water":"water"}},"missing_flipbook_textures":[],"$schema":"schemas/textureAtlasMappings.schema.json"}
